CREATE TABLE IF NOT EXISTS bm_benchmark (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    name TEXT NOT NULL,
    client TEXT DEFAULT NULL,
    year INTEGER NOT NULL,
    lang TEXT DEFAULT NULL
); 